# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: 'dist/.*'
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.1.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@7.32.0
          - '@typescript-eslint/eslint-plugin@4.30.0'
          - '@typescript-eslint/parser@4.30.0'
          - eslint-plugin-import@2.24.2
          - eslint-plugin-prettier@4.0.0
          - eslint-plugin-react@7.25.1
          - eslint-plugin-unused-imports@1.1.4
        files: \.tsx?$ # *.js, *.jsx, *.ts and *.tsx
        types: [file]
        args: ['--max-warnings', '0']
  - repo: local
    hooks:
      - id: npm_format
        name: npm format
        entry: npm run format
        language: node
        pass_filenames: false

      - id: tsc
        name: tsc
        entry: npm run lint
        language: node
        files: src/.*
        pass_filenames: false

      - id: npm_test
        name: npm test
        entry: npm run test
        language: node
        pass_filenames: false

      - id: npm_build
        name: npm run build
        entry: npm run build
        language: node
        pass_filenames: false
